server:
  port: 8086
  tomcat:
       uri-encoding: UTF-8
       max-threads: 1000
       min-spare-threads: 30
spring:
  datasource:
    name: system
    url: jdbc:mysql://172.16.0.11:3306/huanxin?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: permission
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

        

#转换之后的文件存储路径
storepath: E:/data/chatfiles/
#sdkappid
SDKAppID: 1400466018
#秘钥
Key: 27583fbf20189fae3274a4cdfecfa62efa7dfa41186498a71a2c139ca298edfa
#管理员账号
ADMINACCOUNT: administrator